baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "pandita"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      xhtml = false

