baseURL = ''
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "pandita"

disableKinds = ["section"]

uglyURLs = "true" 
relativeURLs = "true"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      xhtml = false

  
# https://github.com/Borek78/pandita











